<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Defender.Infrastructure</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Defender.Core\Defender.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Silk.NET.SDL" />
    <PackageReference Include="Ultz.Native.SDL" />
  </ItemGroup>
</Project>
